# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0694594ae850db823a5278378d4a886c541c49c6130b1cca4c20a276b1d93e952b5f447577bd6a91e502ead21f86df71d053f4df1363291a5eea4037172cd2a1

test:
  secret_key_base: b3956c855c6477f38d5befe20c134655487144411031ef8f576184bcd6fb2e41f533827e46eeea906da87cdb68df66a6462071d4a7f2764bc4ef7db971f76720

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
